### PR TITLE
Fix compilation on Ubuntu 22.04.

### LINKED ISSUE #4: Compilation fails on Ubuntu 22.04 due to linker issues.
Hi, thanks for open-sourcing the code! AFAIK, the code is meant to work with newer versions of Linux ("Please run the code with a newer version of Linux and GCC"), but there are some small issues with Ubuntu 22.04.

# Summary

- A small number of files have multiple definitions of the same global variable. This causes linker errors.
- Similarly, `yacc` wants `yydebug` to be extern.

# Environment

```
$ lsb_release -d
Description:    Ubuntu 22.04 LTS
$ uname -r
5.15.0-39-generic
$ gcc --version
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
$ yacc --version
bison (GNU Bison) 3.8.2
```

# Details

The output of `make` is copied below.

```
$ make
...
gcc -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DYYDEBUG  -DLINUX -g -Wall  -o dsdgen s_brand.o s_customer_address.o s_call_center.o s_catalog.o s_catalog_order.o s_catalog_order_lineitem.o s_catalog_page.o s_catalog_promotional_item.o s_catalog_returns.o s_category.o s_class.o s_company.o s_customer.o s_division.o s_inventory.o s_item.o s_manager.o s_manufacturer.o s_market.o s_pline.o s_product.o s_promotion.o s_purchase.o s_reason.o s_store.o s_store_promotional_item.o s_store_returns.o s_subcategory.o s_subclass.o s_warehouse.o s_web_order.o s_web_order_lineitem.o s_web_page.o s_web_promotinal_item.o s_web_returns.o s_web_site.o s_zip_to_gmt.o w_call_center.o w_catalog_page.o w_catalog_returns.o w_catalog_sales.o w_customer_address.o w_customer.o w_customer_demographics.o w_datetbl.o w_household_demographics.o w_income_band.o w_inventory.o w_item.o w_promotion.o w_reason.o w_ship_mode.o w_store.o w_store_returns.o w_store_sales.o w_timetbl.o w_warehouse.o w_web_page.o w_web_returns.o w_web_sales.o w_web_site.o dbgen_version.o joint_distribution.o address.o build_support.o date.o decimal.o dist.o driver.o error_msg.o genrand.o join.o list.o load.o misc.o nulls.o parallel.o permute.o pricing.o print.o r_params.o StringBuffer.o tdef_functions.o tdefs.o text.o scd.o scaling.o release.o sparse.o validate.o -lm
/usr/bin/ld: s_purchase.o:/<snip>/git/dsb/code/tools/s_purchase.c:55: multiple definition of `nItemIndex'; s_catalog_order.o:/<snip>/git/dsb/code/tools/s_catalog_order.c:56: first defined here
/usr/bin/ld: s_web_order.o:/<snip>/git/dsb/code/tools/s_web_order.c:56: multiple definition of `nItemIndex'; s_catalog_order.o:/<snip>/git/dsb/code/tools/s_catalog_order.c:56: first defined here
/usr/bin/ld: s_web_order_lineitem.o:/<snip>/git/dsb/code/tools/s_web_order_lineitem.c:54: multiple definition of `g_s_web_order_lineitem'; s_web_order.o:/<snip>/git/dsb/code/tools/s_web_order.c:54: first defined here
/usr/bin/ld: w_catalog_page.o:/<snip>/git/dsb/code/tools/w_catalog_page.c:52: multiple definition of `g_w_catalog_page'; s_catalog_page.o:/<snip>/git/dsb/code/tools/s_catalog_page.c:51: first defined here
/usr/bin/ld: w_customer.o:/<snip>/git/dsb/code/tools/w_customer.c:59: multiple definition of `pCountyRecord'; w_customer_address.o:/<snip>/git/dsb/code/tools/w_customer_address.c:60: first defined here
/usr/bin/ld: w_customer.o:/<snip>/git/dsb/code/tools/w_customer.c:62: multiple definition of `pStateRecord'; w_customer_address.o:/<snip>/git/dsb/code/tools/w_customer_address.c:61: first defined here
/usr/bin/ld: w_household_demographics.o:/<snip>/git/dsb/code/tools/w_household_demographics.c:62: multiple definition of `pDemoRecord'; w_customer_demographics.o:/<snip>/git/dsb/code/tools/w_customer_demographics.c:54: first defined here
/usr/bin/ld: w_warehouse.o:/<snip>/git/dsb/code/tools/w_warehouse.c:54: multiple definition of `g_w_warehouse'; s_warehouse.o:/<snip>/git/dsb/code/tools/s_warehouse.c:51: first defined here
/usr/bin/ld: w_web_site.o:/<snip>/git/dsb/code/tools/w_web_site.c:60: multiple definition of `g_w_web_site'; s_web_site.o:/<snip>/git/dsb/code/tools/s_web_site.c:51: first defined here
collect2: error: ld returned 1 exit status
make: *** [makefile:233: dsdgen] Error 1
```

### PR DESCRIPTION
**Pull request by lmwnshn**
This PR fixes compilation errors on Ubuntu 22.04 caused by linkage issues (fix #4).

Please see the commit log for a quick summary of changes.

# Notes

1. I hope I preserved the right semantics with "what to extern" vs. "what to split into its own global variable", but you should probably check.
2. Additionally, `y.tab.c` and `y.tab.h` are build-time files that have been checked into source control. They changed because I am using a slightly newer version of Bison (you use 3.5.1, I use 3.8.2). Do you want them in the PR?
```
 code/tools/y.tab.c | 1114 ++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------------------------------------------
 code/tools/y.tab.h |  120 ++++++++------
 2 files changed, 554 insertions(+), 680 deletions(-)
```

Thanks!

### CODE REVIEW

**Comment by lmwnshn** [comment]
@microsoft-github-policy-service agree

File: code/tools/QgenMain.c [hunk 1]
```diff
@@ -68,7 +68,7 @@ int g_nQueryNumber,
 StringBuffer_t *g_sbTemplateName = NULL;
 
 
-int yydebug;
+extern int yydebug;
```
Comment (bailud) [inline code/tools/QgenMain.c:71]: This change causes compilation failure on my side. Could you revert this change and see if it compiles on your side?

**Review by bailud — CHANGES_REQUESTED** [review]

File: code/tools/QgenMain.c (hunk 1 above)
Comment (lmwnshn) [reply code/tools/QgenMain.c:71]: I tried reverting the change; without externing `yydebug`, I get a linker error when trying to compile `dsqgen`:

```
$ make
...
gcc -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DYYDEBUG  -DLINUX -g -Wall  -o dsqgen address.o date.o decimal.o dist.o error_msg.o expr.o eval.o genrand.o grammar_support.o keywords.o list.o nulls.o print.o permute.o QgenMain.o query_handler.o r_params.o scaling.o StringBuffer.o substitution.o tdefs.o text.o tokenizer.o w_inventory.o y.tab.o release.o scd.o build_support.o parallel.o  utility.o -lm
/usr/bin/ld: y.tab.o:/home/wanshenl/git/dsb/code/tools/y.tab.c:1245: multiple definition of `yydebug'; QgenMain.o:/home/wanshenl/git/dsb/code/tools/QgenMain.c:71: first defined here
collect2: error: ld returned 1 exit status
make: *** [makefile:235: dsqgen] Error 1
```

My environment is the following:
```
$ lsb_release -cdr
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
$ uname -r
5.15.0-39-generic
$ gcc --version
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
$ bison --version
bison (GNU Bison) 3.8.2
$ flex --version
flex 2.6.4
```

Hmm. I will try to look for a workaround.

Comment (lmwnshn) [reply code/tools/QgenMain.c]: I found a workaround that involves specifying `-fcommon` as a `gcc` compiler flag. The details are in the commit message for the last commit (`42896f5`), essentially, `gcc-10` changed default behavior for whether the linker can merge global variables with the same name.

I wonder if you will have similar compilation errors for the other variables that I externed,
if so, please let me know and I will remove those `extern`s too.

I tested a bit further, just the addition of `-fcommon` is enough to make all of the initial code compile on my environment.
However, while `-fcommon` is safe to use for `yydebug` since there should only be one instance of that variable,
the other variables that I renamed and externed may not be safe to combine as they seem to be conceptually distinct.
For example, `pDemoRecord` was originally defined in two ways:

```
// w_customer_demographics.c
                int nMaxAttribute = distsize("gender") * distsize("education") * distsize("marital_status");
		int nKey = (int)get_rowcount(CUSTOMER_DEMOGRAPHICS);
		pDemoRecord = initializeCharAttributeKeyRecord(nMaxAttribute, nKey);

// w_household_demographics.c
                int nMaxAttribute = distsize("buy_potential") * distsize("dependent_count");
		int nKey = (int)get_rowcount(HOUSEHOLD_DEMOGRAPHICS);
		pDemoRecord = initializeCharAttributeKeyRecord(nMaxAttribute, nKey);
```

and it seems like we would not want to merge these definitions together.

So I think we would want to (1) specify `-fcommon` and (2) keep the variable renaming from this PR.

Thanks!

Comment (bailud) [reply code/tools/QgenMain.c]: > I tried reverting the change; without externing `yydebug`, I get a linker error when trying to compile `dsqgen`:
> 
> ```
> $ make
> ...
> gcc -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DYYDEBUG  -DLINUX -g -Wall  -o dsqgen address.o date.o decimal.o dist.o error_msg.o expr.o eval.o genrand.o grammar_support.o keywords.o list.o nulls.o print.o permute.o QgenMain.o query_handler.o r_params.o scaling.o StringBuffer.o substitution.o tdefs.o text.o tokenizer.o w_inventory.o y.tab.o release.o scd.o build_support.o parallel.o  utility.o -lm
> /usr/bin/ld: y.tab.o:/<snip>/dsb/code/tools/y.tab.c:1245: multiple definition of `yydebug'; QgenMain.o:/<snip>/dsb/code/tools/QgenMain.c:71: first defined here
> collect2: error: ld returned 1 exit status
> make: *** [makefile:235: dsqgen] Error 1
> ```
> 
> My environment is the following:
> 
> ```
> $ lsb_release -cdr
> Description:    Ubuntu 22.04 LTS
> Release:        22.04
> Codename:       jammy
> $ uname -r
> 5.15.0-39-generic
> $ gcc --version
> gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
> $ bison --version
> bison (GNU Bison) 3.8.2
> $ flex --version
> flex 2.6.4
> ```
> 
> Hmm. I will try to look for a workaround.

Hi Wan, could you check if yydebug is defined elsewhere in your local repo where the change is not included in the PR? Maybe check if the yydebug is defined in y.tab.c in your local repo, and try to revert that as well and see if it can compile without the linking error.

Comment (lmwnshn) [reply code/tools/QgenMain.c]: Hi Bailu,

As of commit 5a5c3bcaf5f501019203c2c498e33bc746431fed , `git status` returns a clean work tree. From there,

`yydebug` is already defined by DSB: https://github.com/microsoft/dsb/blob/main/code/tools/y.tab.c#L1117
And this definition is active because our CFLAGS include `-DYYDEBUG`, https://github.com/microsoft/dsb/blob/main/code/tools/makefile#L62

Even if I hack the makefile so that it does not regenerate `y.tab.c` (by no-op-ing https://github.com/microsoft/dsb/blob/main/code/tools/makefile#L283-L284),
it will have a link error.

Could you please check if your local environment somehow not including `-DYYDEBUG`?
e.g., maybe you are using an IDE that overrides CFLAGS. I am running directly from the terminal.

---

That said, the latest commit 42896f5647c2da79961d24f634843e603d699729 should have unified behavior across old and new GCC versions, does it still not compile?

Comment (arselzer) [reply code/tools/QgenMain.c]: Hi @lmwnshn 

Thank you for providing the fix!

I also ran into the same problem when trying to run the makefile.

Using your branch at the latest commit, I was able to compile everything without errors.
In case it still helps, the environment I used was the following:

* Ubuntu 22.04.3 LTS
* 6.2.0-33-generic kernel
* gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
* bison (GNU Bison) 3.8.2
* flex 2.6.4

Comment (lmwnshn) [reply code/tools/QgenMain.c]: @arselzer Good to know, thanks for the info. I will link from the issue in case anyone else finds it helpful.

Comment (EvagelineFEI) [reply code/tools/QgenMain.c]: Hi @lmwnshn，
大佬真是救大命了What you do really helps me!! Thanks capybara
